fix: fix an issue in the custom elements bundle where if you set a property on an element programatically before it was upgraded it would shadow the accessors and therefore break any watchers as well. See https://developers.google.com/web/fundamentals/web-components/best-practices\#lazy-properties
ionic-team/stencil pull request #2949
Opened 2021-07-02 13:34 UTC by nphyatt

This fixes an issue in the custom elements bundle where if you set a property on an element before it is upgraded it will forever shadow the accessors and therefore Watchers will no longer fire.

This is related to and potentially fixes #2456 

The approach here is to check if the element `hasOwnProperty` in the `connectedCallback` and unshadow that property and restore the value that was shadowing the accessors by using the setter to reset the value. This is the best practice described here: https://developers.google.com/web/fundamentals/web-components/best-practices#lazy-properties

We were already doing this but only for the lazy loaded bundle. This PR does it for both.

I also had to add logic to the `attributeChangedCallback` because if fires before the `connectedCallback` event and we set the property there so if it's shadowed we end up setting the shadowed property with the original stale value that was set inline. I believe we should thing about moving the logic to set the property outside of `attributeChangedCallback` as is the best practice described here: https://developers.google.com/web/fundamentals/web-components/best-practices#avoid-reentrancy however that seemed like a bit of a can of worms and outside the scope of this fix. 

I've only tested this fix against the custom elements build so I would like to double check it against the lazy build before we merge.

2021-07-02 22:24 UTC, nphyatt commented
I was able to manually test on the lazy bundle and confirm this does fix the issue there as well and works as intended manually. I had thoughts of trying to write some tests around the behavior but it was not immediately clear to me if one could / how one would go about writing a test in which they attempt change a property on a component in the dom before it has been upgraded.

2021-07-07 13:33 UTC, rwaskiewicz requested changes
One minor comment on the JSDoc

2021-07-07 13:33 UTC, rwaskiewicz commented on src/runtime/proxy-component.ts
> +          // https://developers.google.com/web/fundamentals/web-components/best-practices#avoid-reentrancy
I took a stab at reworking this comment block a section a bit, LMK what you think (especially if I didn't capture the original messaging correctly 🙃)

```suggestion
          // The attributeChangedCallback may run prior to Stencil's connectedCallback, which may also attempt to
          // unshadow lazy properties. The case where an attribute was set inline on the non-upgraded element:
          // ```html
          //    <!-- this component has _not_ been upgraded yet -->
          //    <my-component some-attribute="some-value></my-component>
          // ```
          //  and the property was subsequently set programmatically shall be handled here.
          //
          //  The case where the attribute was set inline but was not set programmatically shall be handled/unshadowed
          //  by connectedCallback.
          //
          //  https://developers.google.com/web/fundamentals/web-components/best-practices#lazy-properties
          //
          //  TODO(STENCIL-16) we should think about whether or not we actually want to be reflecting the attributes to
          //  properties here given that this goes against best practices outlined here
          //  https://developers.google.com/web/fundamentals/web-components/best-practices#avoid-reentrancy
```

2021-07-07 14:23 UTC, rwaskiewicz commented
Tested manually with https://github.com/kensodemann/demo-stencil-watch/commit/da64cc780a8f7cd3c40c0cdd78342372d34d1392 for Custom Elements Build and Lazy Loading. For both of these, I checked out this branch, rebased it off the HEAD of `master` (since the branch doesn't include the fix for running `npm i` on an M1), then ran `npm ci && npm build && npm pack`

In the `demo-stencil-watch` repo's directory, I installed base deps, then the tarball from my local filesystem and built:
`npm ci && npm i <PATH_TO_TARBALL> && npm run build`

Using `http-server` I could then serve the custom element bundle:
```
http-server -c0 site
```
or the lazy bundle:
```
http-server -c0 www
```

For the custom elements bundle and the lazy loaded bundle, it's important to alter the `index.html` file in `site` and `src`, respectively.

The easiest way to test is to uncomment the invocation of `runTest()` and comment out the `customElements.whenDefined` call:
```diff
-    // runTest();
-    customElements.whenDefined('my-component').then(runTest);    
+    runTest();
+    // customElements.whenDefined('my-component').then(runTest);
```

2021-07-07 15:22 UTC, rwaskiewicz commented on src/runtime/proxy-component.ts
> +          //  unshadow lazy properties. If we attempt to unshadow in both places
```suggestion
          // unshadow lazy properties. If we attempt to unshadow in both places
```

2021-07-07 15:22 UTC, rwaskiewicz commented on src/runtime/proxy-component.ts
> +          // we should think about whether or not we actually want to be reflecting the attributes to properties
Can we add the TODO that I originally proposed here? I'd like to start tracking things like this in our planning tools (I may have created a placeholder ticket 😉).
```suggestion
          // TODO(STENCIL-16) we should think about whether or not we actually want to be reflecting the attributes to properties
```

Or did you want to have that conversation as a part of this ticket?

2021-07-07 16:30 UTC, rwaskiewicz commented on src/runtime/proxy-component.ts
> +          //  will be called with `newValue = "some-value"` and will set the shadowed property (this.someAttribute = "another-value"
```suggestion
          //  In this case if we do not unshadow here and use the value of the shadowing property, attributeChangedCallback
          //  will be called with `newValue = "some-value"` and will set the shadowed property (this.someAttribute = "another-value")
```

2021-07-07 16:30 UTC, rwaskiewicz commented on src/runtime/proxy-component.ts
> +          //  to the value that was set inline i.e. "some-value" from above example and when
```suggestion
          //  to the value that was set inline i.e. "some-value" from above example. When
```

2021-07-07 16:55 UTC, rwaskiewicz approved these changes

2021-07-07 16:57 UTC, merged