chore(lint): turn on eslint prefer-rest-params rule
ionic-team/stencil pull request #3387
Opened 2022-05-27 15:50 UTC by alicewriteswrongs

Add the prefer-rest-params rule to our eslint config. This basically
just prefers `...rest: string[]` over accessing `arguments` directly
within a function body.

See https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/src/configs/eslint-recommended.ts#L29

🚨 **NOTE** 🚨: this PR has #3386 as it's base. Either it should be merged into #3386 or it should be merged into main after #3386 merges.

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Build (`npm run build`) was run locally and any changes were pushed
- [ ] Unit tests (`npm test`) were run locally and passed
- [ ] E2E Tests (`npm run test.karma.prod`) were run locally and passed
- [ ] Prettier (`npm run prettier`) was run locally and passed

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

GitHub Issue Number: N/A

## What is the new behavior?

This just enables the rule, fixes violations of it, and then does a (little bit) of unrelated cleanup in one file that was touched. I also filed a tech debt issue for another file that was touched.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Testing

## Other information

2022-05-31 19:23 UTC, alicewriteswrongs commented
@rwaskiewicz it should be good to merge now

2022-06-01 12:01 UTC, rwaskiewicz requested changes
One small ask on the shims

2022-06-01 13:15 UTC, alicewriteswrongs commented on src/client/polyfills/css-shim/css-parser.ts
> +function _expandUnicodeEscapes(s: string, ...rest: string[]): string {
Sure, that makes sense

2022-06-01 14:44 UTC, rwaskiewicz approved these changes

2022-06-01 14:44 UTC, merged