Ap/remove unused exports fs watch rebuild
ionic-team/stencil pull request #3416
Opened 2022-06-13 21:17 UTC by alicewriteswrongs

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Build (`npm run build`) was run locally and any changes were pushed
- [ ] Unit tests (`npm test`) were run locally and passed
- [ ] E2E Tests (`npm run test.karma.prod`) were run locally and passed
- [ ] Prettier (`npm run prettier`) was run locally and passed

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

GitHub Issue Number: N/A

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Testing

## Other information

2022-06-15 20:19 UTC, rwaskiewicz requested changes
Two small asks to fix lint errors

2022-06-15 20:19 UTC, rwaskiewicz commented on src/compiler/fs-watch/fs-watch-rebuild.ts
> + * @param ext a file extension
Should this be something more like:
```suggestion
 * Helper to check if an extension is found in our list of script extensions
 * @param filePath the path of a file to check
```

I'm not entirely sure the summary on the first line aligns with what we're doing here. Thoughts?

2022-06-15 20:19 UTC, rwaskiewicz commented on src/compiler/fs-watch/fs-watch-rebuild.ts
> + * @param ext a file extension
Should this be something more like:
```suggestion
 * Helper to check if an extension is found in our list of style extensions
 * @param filePath the path of a file to check
```
I'm not entirely sure the summary on the first line aligns with what we're doing here. Thoughts?

2022-06-16 12:04 UTC, rwaskiewicz commented
@alicewriteswrongs looks like lint (specifically Prettier) is failing for us for this PR

2022-06-17 14:39 UTC, alicewriteswrongs commented
@rwaskiewicz should be updated now

2022-06-21 12:41 UTC, rwaskiewicz approved these changes
LGTM!

2022-06-21 13:33 UTC, merged