test(config): add unit tests to config flags
ionic-team/stencil pull request #3425
Opened 2022-06-16 18:09 UTC by rwaskiewicz

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Unit tests (`npm test`) were run locally and passed
- [ ] E2E Tests (`npm run test.karma.prod`) were run locally and passed
- [x] Prettier (`npm run prettier`) was run locally and passed

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

the initialization of `config.flags` is not tested

GitHub Issue Number: N/A

## What is the new behavior?

this commit adds unit tests to the portion of the configuration
validation process for the 'flags' field

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Testing

unit tests pass

## Other information

2022-06-17 21:46 UTC, alicewriteswrongs requested changes
just one thing I noticed

2022-06-17 21:46 UTC, alicewriteswrongs commented on src/compiler/config/test/validate-config.spec.ts
> +      it('sets "devMode" to false the user provided flag isn\'t a boolean', () => {
```suggestion
      it('sets "devMode" to false if the user provided flag isn\'t a boolean', () => {
```

2022-06-17 21:46 UTC, alicewriteswrongs commented on src/compiler/config/test/validate-config.spec.ts
> +      it('sets "devMode" to false the user provided flag isn\'t a boolean', () => {
or `"when"`, possibly?

2022-06-21 11:45 UTC, rwaskiewicz commented on src/compiler/config/test/validate-config.spec.ts
> +      it('sets "devMode" to false the user provided flag isn\'t a boolean', () => {
Yeah, that makes sense!

2022-06-21 14:11 UTC, alicewriteswrongs approved these changes
lgtm!

2022-06-21 14:34 UTC, merged