misc(eslint): add auto-sort for imports/exports
ionic-team/stencil pull request #3583
Opened 2022-09-06 20:55 UTC by tanner-reits

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Build (`npm run build`) was run locally and any changes were pushed
- [ ] Unit tests (`npm test`) were run locally and passed
- [ ] E2E Tests (`npm run test.karma.prod`) were run locally and passed
- [ ] Prettier (`npm run prettier`) was run locally and passed

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [X] Other (please describe):
Adds eslint plugin for auto-sort imports and exports

## What is the current behavior?

GitHub Issue Number: N/A

## What is the new behavior?

Imports and exports will no have eslint errors when not in standard order

## Does this introduce a breaking change?

- [ ] Yes
- [X] No

## Testing

## Other information

If in VS code, you can also enable "code actions" to run on save that will automatically resolve auto-sort errors

2022-09-06 21:22 UTC, rwaskiewicz reviewed
I have 1 question and 1 ask for this PR:

- Why 'simple-import-sort' over other import plugins in the ESLint ecosystem? Does this provide any benefit over others? 
- Can you create one (maybe more) additional commits on this branch for me? 
   - One commit with the contents of running `npm run lint -- --fix`
   - Run `npm run lint -- --fix` one more time, if there are changes from the second run, can you commit those separately
   - Run `npm run prettier` and commit those changes (if there are any)?

2022-09-07 14:43 UTC, tanner-reits commented
> I have 1 question and 1 ask for this PR:
> 
> * Why 'simple-import-sort' over other import plugins in the ESLint ecosystem? Does this provide any benefit over others?
> * Can you create one (maybe more) additional commits on this branch for me?
>   
>   * One commit with the contents of running `npm run lint -- --fix`
>   * Run `npm run lint -- --fix` one more time, if there are changes from the second run, can you commit those separately
>   * Run `npm run prettier` and commit those changes (if there are any)?

I can add those commits. As for your question, I don't have a ton of reasoning other than I've used this in the past and like how it breaks-up relative imports from others. It also has quite a few weekly downloads on npm so should stay maintained 🤞

2022-09-12 20:37 UTC, rwaskiewicz commented
Thanks!

For clarity, the reason I asked for those extra steps is that I've spent a good deal of time worrying about import order prior to Stencil 😆 Specifically, I was curious running the tool again would result in another round of import changes (which it doesn't appear to have happened/is good IMO) and if there was any formatting fallout (looks like there was).  IMO the formatting is fine, I'm not staunchly opposed to running lint -> format. However, since lint can now break what was previously a "good" format, can you do me a favor and switch the order of these two steps in CI? https://github.com/ionic-team/stencil/blob/main/.github/workflows/lint-and-format.yml#L19-L24

It looks like this tooling handles side effect imports to the best of its ability, going through the README.  I think we may just have to rely on CI to catch some of these types of things for us

2022-09-12 20:37 UTC, rwaskiewicz requested changes
Since lint can now break what was previously a "good" format, can you do me a favor and switch the order of these two steps in CI? https://github.com/ionic-team/stencil/blob/main/.github/workflows/lint-and-format.yml#L19-L24****

2022-09-13 13:41 UTC, rwaskiewicz approved these changes

2022-09-13 13:41 UTC, rwaskiewicz commented on src/compiler/config/outputs/validate-angular.ts
>  import { OutputTargetAngular } from '../../../declarations';
Heh - I wouldn't change this (since I removed this file in the `v3.0.0-dev` branch). Just funny

2022-09-13 13:41 UTC, rwaskiewicz commented on src/testing/platform/index.ts
>  export * from '@runtime';
The export behavior of this library is interesting 🤔

2022-09-13 14:40 UTC, alicewriteswrongs approved these changes
I like it 👍

2022-09-13 15:17 UTC, merged