refactor(types): drop strictNullChecks count in cli
ionic-team/stencil pull request #3632
Opened 2022-09-26 13:23 UTC by rwaskiewicz

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Build (`npm run build`) was run locally and any changes were pushed
- [ ] Unit tests (`npm test`) were run locally and passed
- [ ] E2E Tests (`npm run test.karma.prod`) were run locally and passed
- [ ] Prettier (`npm run prettier`) was run locally and passed

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

GitHub Issue Number: N/A

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Testing

## Other information

2022-09-26 16:10 UTC, alicewriteswrongs requested changes
mostly looks good to me, just had a few questions

2022-09-27 11:28 UTC, rwaskiewicz commented on src/cli/telemetry/test/helpers.spec.ts
> +  it('returns true when the flag "true" flag is false', () => {
yeah, good catch - I meant to rename these and forgot 🤦

2022-09-27 11:35 UTC, rwaskiewicz commented on src/cli/find-config.ts
>    let configPath = opts.configPath;
It's not, at least as far as the TS type system is concerned. The issue we were running into was the `configPath: null as string,` in the original type, which was the cause of the strictNull check - TS wasn't smart enough to see that `results.configPath` would always be assigned to a string, which is why we do this reordering here

2022-09-27 15:15 UTC, alicewriteswrongs approved these changes
lgtm! 👍

2022-09-27 18:25 UTC, tanner-reits approved these changes
lgtm!

2022-09-27 19:26 UTC, merged