fix(compiler): move `inlindeDynamicImports` to Rollup output
ionic-team/stencil pull request #3789
Opened 2022-11-02 22:15 UTC by tanner-reits

This commit updates the `inlineDyamicImports` Rollup config option to be moved to the `output` section of the config as the root-level config is deprecated. This also resolves an issue that was causing build errors when the flag was set on `dist-custom-elements` due to multiple inputs

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [X] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [X] Build (`npm run build`) was run locally and any changes were pushed
- [X] Unit tests (`npm test`) were run locally and passed
- [X] E2E Tests (`npm run test.karma.prod`) were run locally and passed
- [X] Prettier (`npm run prettier`) was run locally and passed

## Pull request type

 

 

Please check the type of change your PR introduces:
- [X] Bugfix
- [ ] Feature
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Currently, setting `inlineDynamicImports` on the `dist-custom-elements` output target will result in a build error

GitHub Issue Number: N/A

## What is the new behavior?

- Updates our mapping of `inlineDynamicImports` in our `BundleOptions` interface to a Rollup config so that the option is set as a part of the `output` config object. This is the new approach as the root option was marked as deprecated (https://rollupjs.org/guide/en/#outputinlinedynamicimports)
- Also adds logic so the option can only be set when the number of inputs to the bundler is 1 or fewer (this is the error that was being thrown during the build process before)

## Does this introduce a breaking change?

- [ ] Yes
- [X] No

## Testing

- Verified the build was successful
- Added unit tests for the changes and conditional logic

## Other information

I looked at Amplitude to see if the option was actual used on `dist-custom-elements` and looked like there were some instances of it recently (not sure how since builds likely would've been failing). But, for now I think we should keep that option around

2022-11-08 14:30 UTC, rwaskiewicz requested changes
A few additional asks:

1. Can we update the testing section as to how we tested this for `lazy`, `hydrate` and `custom-elements`? I see this field being used in a few places not explicitly called out, and want to make sure we have it covered:
![Screen Shot 2022-11-08 at 9 26 12 AM](https://user-images.githubusercontent.com/1930213/200590349-79232bbc-d4a0-4e7a-bf36-2fd16296f666.png)
2. Can we add JSDoc to the fields (`src/compiler/bundle/bundle-interface.ts#BundleOptions.inlineDynamicImports`) and the `inlineDynamicImports` fields for the output targets in the public compiler type interface?
3. Can we update the docs with this field?

2022-11-08 14:30 UTC, rwaskiewicz commented on src/compiler/bundle/bundle-output.ts
> +      inlineDynamicImports: bundleOpts.inlineDynamicImports ? Object.keys(bundleOpts.inputs).length <= 1 : false,
For my own edification, in what scenarios is `bundleOpts.inputs` equal to zero? This might be something worth adding a comment to

2022-11-08 14:30 UTC, rwaskiewicz commented on src/compiler/bundle/test/bundle-output.spec.ts
> +      expect((options.output as OutputOptions).inlineDynamicImports).toBe(false);
I really wish there was a way for `expect` assertions to narrow a type for us. `options.output` could feasibly be `undefined`, `OutputOptions`, or `OutputOptions[]`. Could we add a few assertions to make using this assertion a little safer for us?
```
      expect(options.output).toBeDefined();
      expect(Array.isArray(options.output)).toBe(false);
```

2022-12-08 01:54 UTC, tanner-reits commented
@rwaskiewicz I took another look at this, and, honestly, we might want to just remove the `inlineDynamicImports` option from `dist-custom-elements` (and `dist-custom-elements-bundle`, but obviously that's going away anyway).

My reasoning is, the option is only valid if the number of inputs is one or less. But, for those targets, there will always be at least two "inputs" because we have the "core" input and then any components. Which, nobody is going to have a Stencil lib without any components in it 😂 

We'll still keep the option around for the `BundleOptions` since we hard-set that `true` for the hydrate app bundling.

2022-12-08 20:27 UTC, rwaskiewicz commented
@tanner-reits I think I'm OK with that 👍

2022-12-08 21:41 UTC, alicewriteswrongs commented
me too! :+1:

2022-12-09 14:48 UTC, closed without merging