fix(cli): ensure that argument order is correct for Jest
ionic-team/stencil pull request #3827
Opened 2022-11-16 18:41 UTC by alicewriteswrongs

This ensures that CLI arguments are ordered correctly when we pass them to Jest. In particular, we want to ensure that all flags of the type `--maxWorkers=0` and the like are _before_ any flags which we don't know about, like `my-spec-file.ts` (the latter being actually a match pattern for which spec files to run).

In other words, if the user passes arguments like this:

```
--e2e foo.spec.ts
```

or

```
--e2e -- foo.spec.ts
```

We need to ensure we use something like

```
["--e2e", "foo.spec.ts"]
```

to generate the Jest config.

The wrinkle is that after we've parsed our known CLI arguments (in the `cli` module) we do some addition modification of the arguments, based on values set in the `Config`, in the `buildJestArgv` function. In particular, we'll look to see if a `maxWorkers` flag is already passed and, if not, we add one to the args before they're used to build the Jest configuration.

Before this change that would result in an array like this being passed to Jest:

```
["--e2e", "foo.spec.ts", "--maxWorkers=0"]
```

because we simply stuck the new `--maxWorkers` arg right on the end of the already-combined array (combined because it's basically `knownArgs + unknownArgs`). No good!

Instead, we modify a copy of `knownArgs` with flags like this and then produce a new, combined array to pass to Jest when we're all done, so it looks like this instead:

```
["--e2e", "--maxWorkers=0", "foo.spec.ts"]
```

Much better!

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Build (`npm run build`) was run locally and any changes were pushed
- [ ] Unit tests (`npm test`) were run locally and passed
- [ ] E2E Tests (`npm run test.karma.prod`) were run locally and passed
- [ ] Prettier (`npm run prettier`) was run locally and passed

## Pull request type

 

 

Please check the type of change your PR introduces:
- [x] Bugfix
- [ ] Feature
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

In certain cases passing a filename pattern to `stencil test` will not cause the right test files to run. Boo!

## What is the new behavior?

The bug is fixed by re-ordering arguments before they're using to generate a Jest configuration.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Testing

There are reproductions linked in both #3785 and #3825. I confirmed that the fix addressed both of those issues, and also added regression tests which fail without the fix.

## Other information

2022-11-16 20:28 UTC, rwaskiewicz approved these changes

2022-11-17 14:07 UTC, tanner-reits requested changes
One small thing to confirm. If it's not a problem, then this looks good!

2022-11-17 14:07 UTC, tanner-reits commented on src/testing/jest/jest-config.ts
> +  const args: ReadonlyArray<string> = [...knownArgs, ...config.flags.unknownArgs];
UnknownArgs doesn't get mutated anywhere, correct? I just noticed we created a copy before with `slice` but not doing that here. Probably okay, just erring on the side of caution

2022-11-17 15:12 UTC, tanner-reits commented on src/testing/jest/jest-config.ts
> +  const args: ReadonlyArray<string> = [...knownArgs, ...config.flags.unknownArgs];
Nope you're good. Just making sure it was an intentional change!

2022-11-17 15:12 UTC, tanner-reits approved these changes

2022-11-17 18:41 UTC, merged

2022-12-06 01:02 UTC, bamsargeant commented
# Bug

## Details
Unable to run single e2e test after upgrading from _v2.16.1_ to _v2.19.3_

Command used: `npx stencil test --e2e dialog.e2e.ts`

## Work around
I am able to get the same functionality by adding `--` as an extra arg

Command used: `npx stencil test --e2e -- dialog.e2e.ts`

## Screenshots

### v2.16.1
![image](https://user-images.githubusercontent.com/8199374/205779216-03966fd1-452c-4e9d-9642-81c38048b817.png)

### v2.19.3
![image](https://user-images.githubusercontent.com/8199374/205779088-7b4d28dd-217f-4f62-a74c-a85a3b98ba53.png)

### v2.19.3 with workaround
![image](https://user-images.githubusercontent.com/8199374/205779425-2dc0b7ec-852d-422a-a915-925aa249cfbd.png)