chore(config): mark extras.safari10 field as deprecated
ionic-team/stencil pull request #3899
Opened 2022-12-09 16:34 UTC by alicewriteswrongs

Stencil v3 will deprecate support for Safari 10, so we no longer need to
support this option. This commit marks it as deprecated, as a
preparation for
removing it later.

BREAKING CHANGES: the `safari10` field is now deprecated. Support for
Safari 10 has been dropped.

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Build (`npm run build`) was run locally and any changes were pushed
- [ ] Unit tests (`npm test`) were run locally and passed
- [ ] E2E Tests (`npm run test.karma.prod`) were run locally and passed
- [ ] Prettier (`npm run prettier`) was run locally and passed

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [x] Other (please describe): deprecation

## What is the current behavior?

## What is the new behavior?

This deprecates the `safari10` field on `config.extras`.

## Does this introduce a breaking change?

- [x] Yes
- [ ] No

Users of the `safari10` field should rename it to `__deprecated__safari10` and look to drop support for Safari 10 soon.

## Testing

## Other information

2022-12-13 13:56 UTC, rwaskiewicz requested changes
Changes looks good, I think once https://github.com/ionic-team/stencil/pull/3895 lands, we can get the `BREAKING_CHANGES.md` document-structure related changes after a rebase. From there, can you add:
- these changes to `BREAKING_CHANGES.md`
- links back to the docs site PRs?

2022-12-16 17:28 UTC, alicewriteswrongs commented
Just pushed after addressing merge conflicts, this should hopefully be ready to go now

2022-12-16 18:09 UTC, rwaskiewicz commented
https://github.com/ionic-team/stencil-site/pull/957

2022-12-16 18:09 UTC, rwaskiewicz requested changes

2022-12-16 18:09 UTC, rwaskiewicz commented on BREAKING_CHANGES.md
> +The `extras.safari10` option actives a patch for ES module support in Safari10.
Or do we want to sync this with https://github.com/ionic-team/stencil-site/pull/957?

2022-12-16 19:31 UTC, alicewriteswrongs commented on BREAKING_CHANGES.md
> +The `extras.safari10` option actives a patch for ES module support in Safari10.
good catch, I just copied the wording from https://github.com/ionic-team/stencil-site/pull/957

2022-12-19 13:20 UTC, rwaskiewicz approved these changes

2022-12-19 14:35 UTC, merged