chore(config): add `hydratedFlag` to ValidatedConfig
ionic-team/stencil pull request #3954
Opened 2023-01-05 14:51 UTC by alicewriteswrongs

This adds the `hydratedFlag` property to the `ValidatedConfig` object, meaning that the field must be present.

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Build (`npm run build`) was run locally and any changes were pushed
- [ ] Unit tests (`npm test`) were run locally and passed
- [ ] E2E Tests (`npm run test.karma.prod`) were run locally and passed
- [ ] Prettier (`npm run prettier`) was run locally and passed

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

GitHub Issue Number: N/A

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Testing

## Other information

2023-01-17 19:54 UTC, tanner-reits approved these changes
LGTM! Thanks for the explainer in the description

2023-01-18 15:25 UTC, rwaskiewicz reviewed
Looks good to me, nothing but nitpicks on my end.

2023-01-18 15:25 UTC, rwaskiewicz commented on src/declarations/stencil-public-compiler.ts
> +type StrictConfigFields = 'flags' | 'logger' | 'outputTargets' | 'rootDir' | 'sys' | 'testing' | 'hydratedFlag';
Minor, can we keep this list alphabetized?

2023-01-18 15:25 UTC, rwaskiewicz commented on src/testing/mocks.ts
> +    hydratedFlag: null,
Minor, can we keep this list alphabetized?

2023-01-18 15:25 UTC, rwaskiewicz commented on src/compiler/sys/config.ts
> +    hydratedFlag: userConfig.hydratedFlag ?? null,
Minor, can we keep this list alphabetized?

2023-01-18 15:25 UTC, rwaskiewicz commented on src/compiler/config/validate-config.ts
> +    hydratedFlag: validateHydrated(config),
Minor, can we keep this list alphabetized?

2023-01-18 16:13 UTC, rwaskiewicz requested changes
@alicewriteswrongs looks like we introduce 2 new strict null checks violations here as well (the readout from the GH Action only compares against `main`). Can you TAL at that as well?

2023-01-18 18:57 UTC, rwaskiewicz approved these changes

2023-01-18 19:10 UTC, alicewriteswrongs commented
Ok so I don't _think_ there are any new SNC errors introduced by the PR. To verify that I did the following

### get null errors on branch

```sh
git checkout ap/validate-hydrate-flag
npm ci && npm run build
npx tsc --strictNullChecks --noEmit --pretty false > /tmp/null_errors_pr.txt
```

### get null errors on V3

```sh
git checkout v3.0.0-dev
npm ci && npm run build
npx tsc --strictNullChecks --noEmit --pretty false > /tmp/null_errors_v3.txt
```

### compare

```sh
cd /tmp
diff null_errors_pr.txt null_errors_v3.txt
```

and I didn't see any differences in the files. also if I do:

```sh
cat /tmp/null_errors_pr.txt
cat /tmp/null_errors_v3.txt
```

I get 

```
2919
2919
```

2023-01-18 19:14 UTC, merged