chore(release): update build id, version generation
ionic-team/stencil pull request #4098
Opened 2023-02-24 16:21 UTC by rwaskiewicz

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Build (`npm run build`) was run locally and any changes were pushed
- [ ] Unit tests (`npm test`) were run locally and passed
- [ ] E2E Tests (`npm run test.karma.prod`) were run locally and passed
- [ ] Prettier (`npm run prettier`) was run locally and passed

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

GitHub Issue Number: N/A

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Testing

## Other information

2023-03-02 16:21 UTC, alicewriteswrongs approved these changes
I think this all makes sense 👍

2023-03-06 15:21 UTC, tanner-reits requested changes
Version logic looks good. Think this needs to be rebased since the `getOptions` testing diff seems off

2023-03-06 15:25 UTC, rwaskiewicz commented
@tanner-reits rebase complete

2023-03-06 15:27 UTC, tanner-reits approved these changes

2023-03-06 15:30 UTC, alicewriteswrongs approved these changes

2023-03-06 15:39 UTC, merged