write exports for defineCustomElement typedefs
ionic-team/stencil pull request #4194
Opened 2023-03-23 23:05 UTC by tanner-reits

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [X] Build (`npm run build`) was run locally and any changes were pushed
- [X] Unit tests (`npm test`) were run locally and passed
- [X] E2E Tests (`npm run test.karma.prod`) were run locally and passed
- [X] Prettier (`npm run prettier`) was run locally and passed

## Pull request type

 

 

Please check the type of change your PR introduces:
- [X] Bugfix
- [ ] Feature
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

The `index.d.ts` file for `dist-custom-elements` when setting `generateTypeDeclarations: true` and `customElementsExportBehavior: 'single-export-module'` would not include exported typedefs for the components' `defineCustomElement` functions.

GitHub Issue Number: Closes #4093 

## What is the new behavior?

The `index.d.ts` file now includes an export for `defineCustomElement` for each component in the bundle

## Does this introduce a breaking change?

- [ ] Yes
- [X] No

## Testing

Verified output in a Stencil starter project and in a consuming application (Angular)

Updated unit tests for the affected code.

## Other information

2023-03-24 17:26 UTC, alicewriteswrongs commented
looks there might be one additional SNC error though - would you mind fixing that while we're in here?

2023-03-28 13:14 UTC, rwaskiewicz requested changes

2023-03-28 13:14 UTC, rwaskiewicz commented on src/compiler/output-targets/dist-custom-elements/custom-elements-types.ts
> +            const localComponentTypeDefFilePath = `./${component.sourceFilePath.split('/').pop()?.replace('.tsx', '')}`;
Can we tighten this replace up by ensuring we only replace '.tsx' if it occurs at the end of the string? I think that'd look something like:
```suggestion
            const localComponentTypeDefFilePath = `./${component.sourceFilePath.split('/').pop()?.replace(/\.tsx$/, '')}`;
```

2023-03-28 15:50 UTC, tanner-reits commented
Made a small change to how the path is generated to the sibling typedef file since when we bundle the code it generates the `.js` and `.d.ts` files from the component tag name _not_ the file name

I did, however, update how we replace the `.tsx` extension for the path to the `dist-types` file so it only strips off the trailing `.tsx` extension (similar to [this comment](https://github.com/ionic-team/stencil/pull/4194#discussion_r1150593965))

2023-03-28 18:28 UTC, alicewriteswrongs approved these changes
lgtm! 👍

2023-03-29 13:37 UTC, rwaskiewicz approved these changes

2023-03-29 18:13 UTC, merged