Treits/fix/jest component disconnected callback
ionic-team/stencil pull request #4269
Opened 2023-04-14 19:04 UTC by tanner-reits

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [X] Build (`npm run build`) was run locally and any changes were pushed
- [X] Unit tests (`npm test`) were run locally and passed
- [X] E2E Tests (`npm run test.karma.prod`) were run locally and passed
- [X] Prettier (`npm run prettier`) was run locally and passed

## Pull request type

 

 

Please check the type of change your PR introduces:
- [X] Bugfix
- [ ] Feature
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

GitHub Issue Number: #4053 

The `disconnectedCallback` will not be called for a component after the test has executed.

## What is the new behavior?

This change will call the `disconnectedCallback` as a part of the `afterEach` for each test that is defined when constructing the Jest test environment.

**NOTE:** This behavior will not call the `disconnectedCallback` for child components. For some reason, the MockDoc implementation does not have reference to child/nested components. So, only the `disconnectedCallback` for `my-component` would be called in the following example:

```html
// my-component.tsx

<div>
  <p>My component</p>
  <my-child-component></my-child-component>
</div>
```

## Does this introduce a breaking change?

- [ ] Yes
- [X] No

## Testing

Tested this with the reproduction from the original Github issue. Hard to write tests around this since this is a change to the testing ecosystem itself.

## Other information

2023-04-17 18:03 UTC, alicewriteswrongs requested changes
I think this looks good! I tried it out with the minimal repro locally and afaict it fixes the issue. It would be good to have _some_ sort of test - could we possibly include a modified version of one of the tests in the reproduction case as a regression test?

2023-04-17 18:20 UTC, rwaskiewicz requested changes
Functionality here appears to work as expected 👍 Had a few asks here before we move forward with this.

2023-04-17 18:20 UTC, rwaskiewicz commented on src/testing/jest/jest-setup-test-framework.ts
I wonder if we could add a test for this either in `end-to-end` or `karma` - thoughts?

2023-04-25 18:24 UTC, tanner-reits commented on src/testing/jest/jest-setup-test-framework.ts
Chatted with @rwaskiewicz about this and came to the conclusion that there isn't a good, reliable way to test the teardown behavior since that logic executes in a global `afterEach()` callback. Hence, trying to spy on any component's `disconnectedCallback` or public class member won't work since a component's teardown wouldn't happen until after the test has finished and any assertions have already run.

2023-04-26 12:30 UTC, alicewriteswrongs approved these changes
lgtm!

2023-04-26 12:42 UTC, rwaskiewicz approved these changes

2023-04-26 15:25 UTC, merged