test(validate-testing): evaluate property checks
ionic-team/stencil pull request #4384
Opened 2023-05-12 19:13 UTC by rwaskiewicz

## What is the current behavior?

GitHub Issue Number: N/A

## What is the new behavior?

- 

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Testing

## Other information

2023-05-16 15:12 UTC, tanner-reits approved these changes

2023-05-17 16:19 UTC, alicewriteswrongs requested changes
noticed a few small things, looks good though!

2023-05-17 16:19 UTC, alicewriteswrongs commented on src/compiler/config/test/validate-testing.spec.ts
> +        // the nature of this test requires using a non-number, hence th type assertion
```suggestion
        // the nature of this test requires using a non-number, hence the type assertion
```

2023-05-17 16:19 UTC, alicewriteswrongs commented on src/compiler/config/test/validate-testing.spec.ts
> +    it('creates an error the value provided is negative', () => {
```suggestion
    it('creates an error if the value provided is negative', () => {
```

2023-05-17 16:19 UTC, alicewriteswrongs commented on src/compiler/config/test/validate-testing.spec.ts
> +    it.each([-0, 0, 0.5, 1.0])(
ah good ol' `-0`, everyone's favorite number

2023-05-17 17:08 UTC, alicewriteswrongs approved these changes

2023-05-17 17:22 UTC, merged