remove safari10 extras flag
ionic-team/stencil pull request #4421
Opened 2023-05-24 22:27 UTC by tanner-reits

Remove the safari10 extras option that was marked as deprecated in v3. This builds upon #4420 

## What is the current behavior?

GitHub Issue Number: N/A

## What is the new behavior?

- 

## Does this introduce a breaking change?

- [X] Yes
- [ ] No

## Testing

## Other information

2023-05-25 14:47 UTC, rwaskiewicz requested changes

2023-05-25 14:47 UTC, rwaskiewicz commented on src/declarations/stencil-public-compiler.ts
> -  __deprecated__safari10?: boolean;
There's a few references to the old property name I found in some of our tests. Can we remove these while we're in here?

I found a few references to the _old_ name (`cssVarsShim`, prior to the rename) in:

- https://github.com/ionic-team/stencil/blob/42314dc202e9832086207759565c6660d3746eff/test/jest-spec-runner/stencil.config.ts#L14
- https://github.com/ionic-team/stencil/blob/42314dc202e9832086207759565c6660d3746eff/test/todo-app/stencil.config.ts#L16
- https://github.com/ionic-team/stencil/blob/42314dc202e9832086207759565c6660d3746eff/test/karma/stencil.config.ts#L37

2023-05-26 11:43 UTC, rwaskiewicz approved these changes

2023-05-26 20:47 UTC, alicewriteswrongs approved these changes
looks great! let's delete!

2023-05-30 16:41 UTC, merged