BREAKING CHANGE: removal of deprecated connect and context APIs
ionic-team/stencil pull request #4437
Opened 2023-05-30 22:36 UTC by JessicaSachs

## What is the current behavior?

GitHub Issue Number: N/A

## What is the new behavior?

- 

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Testing

## Other information

2023-05-31 23:47 UTC, JessicaSachs commented
There's one unit test breaking for the dev build number not matching a particular regexp. Aside from that, the build looks green!

2023-06-02 14:13 UTC, rwaskiewicz requested changes
Looks good! 

I had one minor nitpick in the code.

Only blocking ask is to update the git commit message to follow our [semantic commit message format](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md#commit-message-format)

2023-06-02 14:53 UTC, alicewriteswrongs approved these changes
all looks good! always good to delete some code 🗑️

approval pending the section number change @rwaskiewicz mentioned, also looks like this might need a rebase

2023-06-02 20:45 UTC, rwaskiewicz approved these changes

2023-06-05 13:29 UTC, tanner-reits requested changes
Changes look good, just one question in the breaking changes md

2023-06-05 13:29 UTC, tanner-reits commented on BREAKING_CHANGES.md
> +- [Breaking Changes](#breaking-changes)
Is this a rebase problem or am I missing something? Wouldn't think anything in the v3 section should change

2023-06-05 13:49 UTC, rwaskiewicz commented
@JessicaSachs it looks like the karma tests are now failing - I pulled the branch locally and was able to confirm that this wasn't related to any Browserstack flakiness (IE I was able to repro locally by building this branch locally and with `npm run test.karma.prod` from the root level of the project). Can you PTAL?

2023-06-05 21:45 UTC, tanner-reits approved these changes
Looks good!

2023-06-09 01:02 UTC, merged