fix(compiler): handle static members with stencil decorators
ionic-team/stencil pull request #4463
Opened 2023-06-07 14:24 UTC by rwaskiewicz

## What is the current behavior?

Stencil fails to compile a component that has a static class member that is both initialized and is decorated with Stencil's `@Prop` or `@State` decorators

GitHub Issue Number: #4462 

## What is the new behavior?

this commit fixes an edge case to the fix introduced in 6dbe9a5 (#4447). the mechanism for checking if there is a statically intiialized class member has been updated in order to exclude such members that are decorated with Stencil's `@Prop()` and `@State()` decorators.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Testing

Unit/Karma tests updated/added

I also tested this against #4462's provided repo, as well as a slightly larger component that still compiles/uses more Stencil decorators:
```tsx
import { Component, Event, EventEmitter,  Method, Listen, Prop, State } from '@stencil/core';

@Component({
  tag: 'screen-tools',
})
export class ScreenTools {
  @Prop() static skin = 12
  @State() static skin1 = 12

  @Event() static skinChange: EventEmitter;
  @Listen('todoCompleted')
  static todoCompletedHandler(event: CustomEvent<any>) {
    console.log('Received the custom todoCompleted event: ', event.detail);
  }

  @Method()
  static async changeSkin(skin: string) {
    console.log('skin', skin)
  }
}
``` 

## Other information

2023-06-07 16:02 UTC, alicewriteswrongs requested changes
looks straightforward enough and I believe the karma test!

just had like two little questions

2023-06-07 16:02 UTC, alicewriteswrongs commented on src/compiler/transformers/decorators-to-static/convert-static-members.ts
> +      typeof decoratorName !== 'boolean' && CONSTRUCTOR_DEFINED_MEMBER_DECORATORS.some((val) => val === decoratorName)
are you doing the `.some(...)` stuff to get around the typing for `.includes` ? I created this dumb little [`readOnlyArrayHasStringMember`](https://github.com/ionic-team/stencil/blob/29ae12061984eadd46fe2a73a56a7245e4271cee/src/utils/util.ts#L234-L237) function which could be used for that purpose (it has to do a typecast :/ )

2023-06-07 16:02 UTC, alicewriteswrongs requested changes
looks straightforward enough and I believe the karma test!

just had like two little questions

2023-06-07 16:02 UTC, alicewriteswrongs requested changes
looks straightforward enough and I believe the karma test!

just had like two little questions

2023-06-07 16:02 UTC, alicewriteswrongs requested changes
looks straightforward enough and I believe the karma test!

just had like two little questions

2023-06-07 19:30 UTC, alicewriteswrongs approved these changes

2023-06-12 14:34 UTC, tanner-reits approved these changes
Changes look good. Allowing a `static` modified on `Prop`s and `State`s seems a little bizarre to me, but maybe I don't understand the use case 🤷‍♂️

2023-06-12 14:34 UTC, tanner-reits commented on test/karma/test-app/static-members/karma.spec.ts
> +    expect(cmp.textContent.trim()).toBe('This is a component with static a Stencil decorated member');
non-blocker:

```suggestion
    expect(cmp.textContent.trim()).toBe('This is a component with a static Stencil decorated member');
```

2023-06-12 16:31 UTC, JessicaSachs approved these changes

2023-06-13 13:48 UTC, merged