chore(engines): drop Node 14 support
ionic-team/stencil pull request #4472
Opened 2023-06-12 20:40 UTC by tanner-reits

## What is the current behavior?

Stencil currently support Node 14

GitHub Issue Number: N/A

## What is the new behavior?

Minimum version Stencil supports is now Node 16 🎉  

## Does this introduce a breaking change?

- [X] Yes
- [ ] No

## Testing

## Other information

2023-06-12 20:43 UTC, tanner-reits reviewed
Just noting a few things. Need CI to run to make sure things are looking good and need to test the `fs` changes still. 

Also, the docs site was already updated for v4 node support so don't need to make any changes over there

2023-06-12 20:43 UTC, tanner-reits commented on package.json
> +    "npm": ">=7.10.0"
Pulled these from Node's [previous releases matrix](https://nodejs.org/en/download/releases)

2023-06-13 13:58 UTC, alicewriteswrongs approved these changes

2023-06-13 16:23 UTC, rwaskiewicz requested changes
Can you do me a favor and fill out the testing steps section of this PR for me please?

2023-06-13 16:23 UTC, rwaskiewicz commented on test/karma/package.json
> +    "npm": "8.19.4"
Can we bump `@types/node` while we're in here? ATM, we're pinned at v14

2023-06-13 16:23 UTC, rwaskiewicz commented on test/karma/package.json
> +    "npm": "8.19.4"
In doing this (bump) I believe that'll update the `package-lock.json` to v2 of the package lock format. If that's the case, can you bump the `package-lock.json` files of under `test/karma` too? I think it's just:
- `test/karma/test-sibling`
- `test/karma/test-invisible-prehydration`

2023-06-15 17:50 UTC, rwaskiewicz approved these changes

2023-06-15 17:53 UTC, merged