fix(runtime): add onSelect to textarea and input
ionic-team/stencil pull request #4616
Opened 2023-07-25 15:13 UTC by cam-narzt

## What is the current behavior?
Currently stencil is lacking the `onSelect` attribute on the `<input>` and `<textarea>` html elements, so trying to use them fails to compile.

GitHub Issue Number: N/A

## What is the new behavior?

-  adds the attribute to these elements.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Testing

I monkey patched this into my app which then was able to compile and the attribute was added to the html element correctly.

## Other information

Apparently this has been around for ages and is well supported:

https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/select_event

https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement/select_event

2023-07-25 20:53 UTC, rwaskiewicz requested changes
Thanks! I had two minor asks, otherwise this looks good to me!

2023-07-25 20:53 UTC, rwaskiewicz commented on src/declarations/stencil-public-runtime.ts
> +    onSelect?: (event: Event) => void;
Can you add the property for `onselect` here as well? (where 'onselect' is all lowercase)
```suggestion
    onSelect?: (event: Event) => void;
    onselect?: (event: Event) => void;
```

2023-07-25 20:53 UTC, rwaskiewicz commented on src/declarations/stencil-public-runtime.ts
> +    onSelect?: (event: Event) => void;
Can you add the property for `onselect` here as well? (where 'onselect' is all lowercase)
```suggestion
    onSelect?: (event: Event) => void;
    onselect?: (event: Event) => void;
```

2023-07-25 21:05 UTC, cam-narzt commented
requested changes done

2023-07-26 13:34 UTC, tanner-reits approved these changes

2023-07-26 13:35 UTC, rwaskiewicz approved these changes
Thanks!

2023-07-26 13:45 UTC, merged