chore(): remove legacy meeting notes and ADRs
ionic-team/stencil pull request #4798
Opened 2023-09-15 18:29 UTC by tanner-reits

Removes the meeting notes in `/notes` and Architecture Decision Docs (ADRs) in `/docs/adr`. 

These docs don't really belong in the repo and don't seem to add any value to the team or external contributors (I have never once referenced these, nor knew they even existed). If we want to migrate any of these over to a design doc or "wiki" article, we can easily recover them from Git history. The only document I made a note about that might worth migrating is the Telemetry stuff, but I can do that when I get around to writing some of these wiki-type docs.

2023-09-15 18:57 UTC, rwaskiewicz requested changes
One small ask - can you remove the `.adr.json` file in the root of the repo as well please?

2023-09-15 19:05 UTC, tanner-reits commented
> One small ask - can you remove the `.adr.json` file in the root of the repo as well please?

Didn't know that was a thing! Thanks for pointing it out. Done in af78331f7277c07ea5bfa2cec0c4c7db8ebf6fbe

2023-09-15 19:08 UTC, rwaskiewicz approved these changes

2023-09-18 13:51 UTC, alicewriteswrongs approved these changes

2023-09-18 17:02 UTC, merged