fix(compiler): consistently generate additional type files
ionic-team/stencil pull request #4938
Opened 2023-10-17 16:25 UTC by HansClaasen

## What is the current behavior?

The if statement doesn't really make sense to me as I would assume you would return early in case no types have changed. However this is causing an interesting side effect where the filesystem in memory determines to delete the directory because the directory and the file in it is not being written. A second execution actually re-creates the file.

It it has hard to determine the origin of this change. Likely this wasn't causing any harm until the memory FS logic started to clear out directories that had no files written to them.

This has potentially a small performance impact since types are now always generated which they would have been before too except the first time. However if we are not writing the file to memory, the directory will be cleaned up by the memfs system when we commit changes in [`writeBuild`](https://github.com/ionic-team/stencil/blob/b91f94a122dc9add876f0277f99afc92c96e66dd/src/compiler/build/write-build.ts#L24).

Fixes #4716

GitHub Issue Number: #4716

## What is the new behavior?

With this patch, we always generate additional type files for the component, including for the first type generation.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Testing

No tests added to verify this new behavior given there aren't any tests for part of the code base already. Given that we don't really know the expected behavior for a lot of these parts I am not sure about the value of adding unit tests for the current state. Happy to do so if you think it does make sense.

## Other information

2023-10-18 20:45 UTC, tanner-reits requested changes
@HansClaasen I think we're good to make the change to avoid the early return, but we'll want to keep the result of `generateAppTypes` around and use it as the return value [here](https://github.com/ionic-team/stencil/blob/ccd3f6ac5cfd26a23603ea86e7682926551256c8/src/compiler/transpile/run-program.ts#L148) for the context where `runTsProgram()` gets executed

2023-10-19 00:44 UTC, HansClaasen commented
@tanner-reits thanks for your review. I made necessary changes, please let me know if they align with what you had in mind. Thank you!

2023-10-19 13:00 UTC, rwaskiewicz approved these changes

2023-10-19 13:49 UTC, tanner-reits approved these changes

2023-10-19 14:07 UTC, merged