feat(testing): allow to set screenshot timeout option in Jest v28+
ionic-team/stencil pull request #5537
Opened 2024-03-20 00:40 UTC by christian-bromann

## What is the current behavior?
When we added support for Jest 28+, we assumed the usage of Jest Circus, the new test runtime for the Jest testing library. With Jest Circus, we lost the ability to configure the timeout related to screenshots in the Stencil Test Runner. This effort adds this support back in.

## What is the new behavior?
Users can define a `screenshotTimeout` option within the Stencil testing configuration which is then passed into the worker.

## Documentation

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Testing

I am working on a reproducible example.

## Other information

n/a

2024-03-20 18:41 UTC, christian-bromann commented
Created a dev build `4.13.0-dev.1710957581.b36e157` which passed the [Framework pipeline](https://github.com/ionic-team/ionic-framework/actions/runs/8363954634) ✅

2024-03-20 19:01 UTC, christian-bromann commented
I updated the PR template and added a repro case. Let me know if this works or if there is a better way to repro this more "realistic".

2024-03-22 12:24 UTC, rwaskiewicz requested changes
All in all looks good!

I had a couple minor asks in the code itself. Other than that, can you add some documentation to the Stencil site regarding this new flag?

Thanks!

2024-03-22 12:24 UTC, rwaskiewicz commented on src/declarations/stencil-public-compiler.ts
> +   * Some JSDoc, describing this field
Can we put something more descriptive here please 🤣

2024-03-22 12:24 UTC, rwaskiewicz commented on src/screenshot/screenshot-compare.ts
> +      screenshotTimeoutMs !== null
Can we update the JSDoc for this logic, now that we don't just set the value to 2500?

2024-03-22 16:35 UTC, christian-bromann commented
Good catch @rwaskiewicz , updated docs.

2024-03-26 14:06 UTC, rwaskiewicz commented
@christian-bromann Changes here look good! Only thing missing from my [original feedback](https://github.com/ionic-team/stencil/pull/5537#pullrequestreview-1954634201) seems to be a PR for the Stencil Site:

> Other than that, can you add some documentation to the Stencil site regarding this new flag?

2024-03-26 16:12 UTC, christian-bromann commented
@rwaskiewicz oh I missed that, added a PR https://github.com/ionic-team/stencil-site/pull/1382

2024-03-27 12:02 UTC, rwaskiewicz approved these changes

2024-03-27 16:51 UTC, merged