fix(compiler): Allow OutputTargetCustom to be called on devMode
ionic-team/stencil pull request #5541
Opened 2024-03-20 15:43 UTC by Sukaato

## What is the current behavior?

GitHub Issue Number: #5514

## What is the new behavior?

In this PR, I've added logic so that OutputTargetCustom can be called in dev mode and not just during build.
OutputTargetCustom can choose when it runs by adding a `task` property to the declaration object.

## Documentation

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Testing

Run stencil tests + manual test with npm link

## Other information

2024-03-25 17:27 UTC, christian-bromann approved these changes
The change looks good to me 👍 

I will have someone else from the @ionic-team/stencil team review this as well.

2024-03-25 17:34 UTC, christian-bromann commented on src/declarations/stencil-public-compiler.ts
> +  task?: 'run' | 'build';
I don't see any docs for custom output targets so having the additional TS doc comment seems sufficient at this point.

2024-04-03 21:20 UTC, alicewriteswrongs requested changes
code itself looks good and I think this change makes sense! Just had a question about the configuration naming

2024-04-03 21:20 UTC, alicewriteswrongs commented on src/declarations/stencil-public-compiler.ts
> +  task?: 'run' | 'build';
For the comment, just a few wording things, and I'm wondering if the variants here and the configuration name should change? Just brainstorming but I'm thinking something like this:

```suggestion
  /**
   * Indicate when the output target should be executed.
   * 
   * - `"onBuildOnly"`: Executed only when `stencil build` is called without `--watch`.
   * - `"always"`: Executed on every build, including in `watch` mode.
   *
   * Defaults to "always".
   */
  taskShouldRun?: 'onBuildOnly' | 'always';
```

2024-04-14 15:14 UTC, Sukaato commented
How can I find out if the compiler is in build mode to retrieve only tasks that have `taskShouldRun: 'onBuildOnly'

2024-04-16 07:05 UTC, christian-bromann commented
@Sukaato the [`BuildOptions`](https://github.com/ionic-team/stencil/blob/641c07a7bddfa63ba521fd157b58a1d284a6badc/scripts/utils/options.ts#L200) have a `isWatch` flag that can help you to determine whether we are in watch mode or not. So if the flag is set you are only call it if the user has set `taskShouldRun` to `always`, otherwise only if `onBuildOnly` is set.

2024-04-16 07:55 UTC, Sukaato commented
Correction done

2024-04-25 19:44 UTC, Sukaato commented
any update @alicewriteswrongs ?

2024-04-30 17:56 UTC, alicewriteswrongs approved these changes

2024-05-01 15:49 UTC, christian-bromann commented
@Sukaato there seems to be a linter issue in `src/declarations/stencil-public-compiler.ts`, mind running `npm run prettier`?

2024-05-01 23:36 UTC, christian-bromann commented
@Sukaato seems like still some lint issues:

```
> npm run prettier.base -- --list-different


> @stencil/core@4.1[7](https://github.com/ionic-team/stencil/actions/runs/8913029708/job/24479044933?pr=5541#step:5:8).2 prettier.base
> prettier --cache "./({bin,scripts,src,test}/**/*.{ts,tsx,js,jsx})|bin/stencil|.github/(**/)?*.(yml|yaml)|*.js" --list-different

src/declarations/stencil-public-compiler.ts
```

2024-05-07 18:49 UTC, alicewriteswrongs approved these changes

2024-05-07 19:05 UTC, merged