Update validate-primary-package-output-target.ts
ionic-team/stencil pull request #5628
Opened 2024-04-07 06:22 UTC by PebblerWon

'rootDir'  is unnecessary

## What is the current behavior?

GitHub Issue Number: N/A

## What is the new behavior?

## Documentation

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Testing

## Other information

2024-04-07 06:28 UTC, PebblerWon commented
'rootDir' is unnecessary

2024-04-08 15:17 UTC, rwaskiewicz requested changes
Hey @PebblerWon 👋 

Thanks for the change! We're open to accepting it 🙂 

We follow semantic commits in this project - can you please run the following on your branch and re-push your branch?
```
git commit --amend -m "chore(validation): remove unneeded path arg

remove `rootDir` from the validation of `normalizePath` for `dist-custom-elements`.
we expect that users will be able to select their own directory for typings, even
if they appear outside of the `rootDir`. this change aligns this output target
with the rest of the output target checks in this file.

"
```

Once that's in, we'll take a second look and merge this.

If you're unable to update the commit message, please feel free to let us know. While we cannot change your branch's commit directly  (or, prefer not to overwrite your branch in your repo if we have write access), we can create a new PR with the error message and give you author credit. 

Either way, let us know - Thanks!

2024-04-08 16:00 UTC, PebblerWon commented
> Hey @PebblerWon 👋
> 
> Thanks for the change! We're open to accepting it 🙂
> 
> We follow semantic commits in this project - can you please run the following on your branch and re-push your branch?
> 
> ```
> git commit --amend -m "chore(validation): remove unneeded path arg
> 
> remove `rootDir` from the validation of `normalizePath` for `dist-custom-elements`.
> we expect that users will be able to select their own directory for typings, even
> if they appear outside of the `rootDir`. this change aligns this output target
> with the rest of the output target checks in this file.
> 
> "
> ```
> 
> Once that's in, we'll take a second look and merge this.
> 
> If you're unable to update the commit message, please feel free to let us know. While we cannot change your branch's commit directly (or, prefer not to overwrite your branch in your repo if we have write access), we can create a new PR with the error message and give you author credit.
> 
> Either way, let us know - Thanks!

Okay, I've changed it.

2024-04-08 16:21 UTC, rwaskiewicz commented
@PebblerWon It looks like your shell might have interpreted those backticks as commands. Mind adding those words back when you get a chance?

2024-04-20 13:31 UTC, PebblerWon commented
> @PebblerWon It looks like your shell might have interpreted those backticks as commands. Mind adding those words back when you get a chance?

I'm sorry, I've changed it.

2024-04-22 12:34 UTC, rwaskiewicz approved these changes
Thanks!

2024-04-22 12:51 UTC, merged