fix(runtime): place scoped component styles after preconnect links but before custom styles
ionic-team/stencil pull request #5938
Opened 2024-08-12 19:53 UTC by christian-bromann

…

## What is the current behavior?
This is an enhancement to a fix we made in in #5926 which caused our Nightly build to fail due to the inability to place custom styles in the HTML template as all component styles were injected last in the `<head />` tag.

STENCIL-1372

## What is the new behavior?
Place scoped component styles after existing preconnect links but allow custom styles to be set at the end of the `<head />` tag.

## Documentation

I will raise a separate PR to the docs page mentioning this behavior.

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Testing

Enhanced existing e2e test.

## Other information

n/a

2024-08-12 20:20 UTC, tanner-reits requested changes
Tested this out with the failing Framework test and still having the same issue. If there are no preconnect links, can we insert the styles where they were going before (i.e. before the first `link` tag)?

2024-08-12 20:49 UTC, christian-bromann commented
Good catch @tanner-reits , I totally missed that use case but added a change with a test.

2024-08-13 14:19 UTC, tanner-reits approved these changes
Looks good in the Framework test case 👍

2024-08-14 00:17 UTC, merged

2024-08-26 18:56 UTC, christian-bromann commented
This patch has been published in Stencil [`v4.21.0`](https://github.com/ionic-team/stencil/releases/tag/v4.21.0)!