fix(compiler): verify parent node when validating component members
ionic-team/stencil pull request #5943
Opened 2024-08-14 01:52 UTC by christian-bromann

## What is the current behavior?
GitHub Issue Number: fixes #5882

## What is the new behavior?
We have missed a case where an import type can come with an empty id.

## Documentation

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Testing

Enhanced existing unit test.

## Other information

n/a

2024-08-16 15:20 UTC, tanner-reits requested changes
Double-checked a couple cases around import aliasing (last change that touched this code) and all looks good there. Only ask is to update the PR title since this was the same title as a previous PR and doesn't reflect the actual change

2024-08-16 16:14 UTC, christian-bromann commented
@tanner-reits dang .. updated title.

2024-08-16 16:15 UTC, tanner-reits approved these changes

2024-08-16 16:22 UTC, merged

2024-08-26 18:53 UTC, christian-bromann commented
This patch was published in Stencil [`v4.21.0`](https://github.com/ionic-team/stencil/releases/tag/v4.21.0)!